module.exports = {
    STARTED: 'STARTED',

    ASK_CURRENCY: 'ASK_CURRENCY',

    ASK_METHOD: 'ASK_METHOD',

    ASK_COUNT: 'ASK_COUNT',

    ASK_AMOUNT: 'ASK_AMOUNT',

    CONFIRMATION: 'CONFIRMATION',

    ASK_PICTURE: 'ASK_PICTURE',

    COMPLETED: 'COMPLETED'
}